# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Erick Cardenas"
description: > # this means to ignore newlines until "email:"
   techie / runner / blogger

email: ecardenascasas@gmail.com
favicon: "/assets/images/favicon.ico"
#blog logo
logo: "/assets/images/ec_logo.jpg"
# blog cover
cover: "/assets/images/site_cover.jpg"

name: 'Erick Rodrigo Cardenas Casas'
author: 'Erick Cardenas'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:       linkedin
    url:        https://linkedin.com/in/ercardenas
    desc:       Connect with me on linkedin
    share_url: 
    share_title:
    share_linl:

#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/ercardenas
    desc:	Follow me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

# Sections shown in the index page

pages_list:
  Blog: 'blog'
  Resume: 'resume'